
services:
  influxdb-v2:
    image: influxdb:2.7.5
    container_name: influxdb-v2
    env_file:
      - ./.env
    volumes:
      - ./influxdb-v2/scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - 8086:8086
    restart: unless-stopped

  telegraf:
    image: telegraf:1.29.5
    container_name: telegraf
    hostname: telegraf
    env_file:
      - ./.env
    volumes:
      - ./telegraf:/etc/telegraf:ro
    cap_add:
      - NET_RAW
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    hostname: grafana
    env_file:
      - ./.env
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    restart: unless-stopped
