{
 "title": "Wi-Fi Client Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_user_var",
    "label": "User",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"fortios_monitor_wifi_controller\", tag: \"user\")"
   },
   {
    "name": "client_mac_var",
    "label": "Client Mac",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\nbucket: \"fortios_monitor_wifi_controller\",\ntag: \"mac\",\npredicate: (r) => r.user == \"$client_user_var\",\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Client Info",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"os\" or r[\"_field\"] == \"manufacturer\" or r[\"_field\"] == \"hostname\" or r[\"_field\"] == \"ip\")\n  |> drop(columns: [\"_time\"])\n  |> last()"
    }
   ]
  },
  { "title": "Placeholder", "type": "state-timeline", "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 } },
  { "title": "Placeholder", "type": "state-timeline", "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 } },
  { "title": "Placeholder", "type": "state-timeline", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Roaming panel",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"wtp_name\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"health_signal_strength_severity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"health_snr_severity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"health_transmission_retry_severity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"health_transmission_discard_severity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"wtp_radio\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mimo\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"vlan_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"channel\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Client rssi/noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"signal\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"noise\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Client snr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Client Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth_rx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth_tx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Client Discard/Retry",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_discard_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"fortios_monitor_wifi_controller\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_client_stats\")\n  |> filter(fn: (r) => r[\"user\"] == \"${client_user_var}\")\n  |> filter(fn: (r) => r[\"mac\"] =~ /${client_mac_var:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_retry_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}