apiVersion: 1

datasources:
  - name: influxdb-v2
    type: influxdb
    access: proxy
    url: http://influxdb-v2:8086
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${FORTIGATE_MONITOR_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}